######################################################################
# Automatically generated by qmake (2.00a) sam. 9. juil. 20:35:49 2005
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
